### ISSUE TITLE
Can't find file README.rst

### ISSUE THREAD

**Issue by xiva-wgt** [russianidiot/public.py#2]
pip public install failed.

Traceback (most recent call last):
  File "setup.py", line 28, in <module>
    setup_cfg_data = read_configuration(path)
  File "setup.py", line 23, in read_configuration
    val = open(val).read()
IOError: [Errno 2] No such file or directory: './README.rst'

create file README.rst into package please or remove depent into code.

**Comment by tarun7singh** [comment]
@xiva-wgt Have you found any workaround to this? I'm not able to install it due to the same error.

**Comment by gdelgado** [comment]
Encountering the same issue here.. Seems the README.rst was not added in the latest update.

**Comment by neil2003tw** [comment]
Same here, README.rst is missing cause error

**Comment by ChamaraPhilipsuom** [comment]
Downgraded to version 0.0.40dev1 and it gave "pbr module not found."
So I installed pbr with `pip install pbr`
It started to work. No problems so far.

**Comment by xiva-wgt** [comment]
@tarun7singh manual added empty file README.rst

**Comment by tarun7singh** [comment]
I installed the 0.0.38 version and everything's working now.

**Comment by sereja8k** [comment]
Same issue here, official repo seems to be damaged or smth.
Installed 0.0.41 from sources and everything is fine.

**Comment by philfreo** [comment]
@russianidiot can you fix this in pypi?

**Comment by johnsgill3** [comment]
Has this issue been fixed?
