### ISSUE TITLE
Clash with atpublic

### ISSUE THREAD

**Issue by jayvdb** [russianidiot/public.py#4]
This installs into namespace `public` , which has been used by PyPI `atpublic` from https://gitlab.com/warsaw/public .

So the two cant be used together on the same host.

How is this better than `atpublic` ?

**Comment by andrewpetrochenkov** [comment]
idk. I do not care, sorry :)

**Comment by jayvdb** [comment]
One difference is that this package supports Python 2.7, while the other one is Python 3.4+ only.
I've raised that at https://gitlab.com/warsaw/public/issues/2
